import { db } from "../";
import { auditLog } from "../schemas/audit_log.schema";
import { USER_IDS } from "./seed-users";

function pad(n: number): string {
	return String(n).padStart(3, "0");
}

export async function seedAuditLogs() {
	console.log("🌱 Seeding audit logs...");

	const userIds = [
		USER_IDS.admin,
		USER_IDS.sales1,
		USER_IDS.sales2,
		USER_IDS.dealer1,
		USER_IDS.dealer2,
		USER_IDS.techSupport1,
	];

	const auditLogData: (typeof auditLog.$inferInsert)[] = [
		// AUTH category
		{
			id: `al_${pad(1)}`,
			userId: USER_IDS.admin,
			category: "AUTH",
			event: "LOGIN_SUCCESS",
			status: "success",
			priority: "low",
			ipAddress: "192.168.1.100",
			userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
			data: { method: "credential" },
			errorMessage: null,
			createdAt: new Date("2024-01-15T08:00:00Z"),
		},
		{
			id: `al_${pad(2)}`,
			userId: null,
			category: "AUTH",
			event: "LOGIN_FAILED",
			status: "error",
			priority: "medium",
			ipAddress: "203.0.113.45",
			userAgent: "curl/7.68.0",
			data: { email: "unknown@hacker.com", attempts: 5 },
			errorMessage: "Invalid credentials",
			createdAt: new Date("2024-02-10T03:15:00Z"),
		},
		{
			id: `al_${pad(3)}`,
			userId: USER_IDS.dealer1,
			category: "AUTH",
			event: "LOGOUT",
			status: "success",
			priority: "low",
			ipAddress: "10.0.0.55",
			userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
			data: null,
			errorMessage: null,
			createdAt: new Date("2024-03-01T17:30:00Z"),
		},
		// PRODUCT category
		{
			id: `al_${pad(4)}`,
			userId: USER_IDS.admin,
			category: "PRODUCT",
			event: "PRODUCT_CREATED",
			status: "success",
			priority: "low",
			ipAddress: "192.168.1.100",
			userAgent: "Mozilla/5.0",
			data: { productId: "prod_00001", serialNumber: "SN-ELECTRICD-00001" },
			errorMessage: null,
			createdAt: new Date("2024-01-16T09:00:00Z"),
		},
		{
			id: `al_${pad(5)}`,
			userId: USER_IDS.sales1,
			category: "PRODUCT",
			event: "PRODUCT_ASSIGNED_TO_DEALER",
			status: "success",
			priority: "low",
			ipAddress: "10.0.1.50",
			userAgent: "Mozilla/5.0",
			data: { productId: "prod_00031", dealerId: "dealer_001" },
			errorMessage: null,
			createdAt: new Date("2024-02-05T10:30:00Z"),
		},
		{
			id: `al_${pad(6)}`,
			userId: USER_IDS.admin,
			category: "PRODUCT",
			event: "DELIVERY_ORDER_UPLOADED",
			status: "success",
			priority: "medium",
			ipAddress: "192.168.1.100",
			userAgent: "Mozilla/5.0",
			data: { doNumber: "DO/2024/001", fileSize: 204800 },
			errorMessage: null,
			createdAt: new Date("2024-01-15T14:00:00Z"),
		},
		{
			id: `al_${pad(7)}`,
			userId: USER_IDS.sales2,
			category: "PRODUCT",
			event: "PRODUCT_IMPORT_FAILED",
			status: "error",
			priority: "high",
			ipAddress: "10.0.1.51",
			userAgent: "Mozilla/5.0",
			data: { filename: "batch_import.csv", rowsFailed: 5 },
			errorMessage: "Duplicate serial numbers detected in import file",
			createdAt: new Date("2024-06-20T11:45:00Z"),
		},
		// DEALER category
		{
			id: `al_${pad(8)}`,
			userId: USER_IDS.admin,
			category: "DEALER",
			event: "DEALER_CREATED",
			status: "success",
			priority: "medium",
			ipAddress: "192.168.1.100",
			userAgent: "Mozilla/5.0",
			data: { dealerId: "dealer_001", dealerName: "Dealer Pratama Tools" },
			errorMessage: null,
			createdAt: new Date("2024-01-10T10:00:00Z"),
		},
		{
			id: `al_${pad(9)}`,
			userId: USER_IDS.admin,
			category: "DEALER",
			event: "DEALER_STATUS_CHANGED",
			status: "success",
			priority: "high",
			ipAddress: "192.168.1.100",
			userAgent: "Mozilla/5.0",
			data: {
				dealerId: "dealer_004",
				previousStatus: "active",
				newStatus: "inactive",
			},
			errorMessage: null,
			createdAt: new Date("2024-04-15T09:30:00Z"),
		},
		{
			id: `al_${pad(10)}`,
			userId: USER_IDS.admin,
			category: "DEALER",
			event: "DEALER_UPDATED",
			status: "success",
			priority: "low",
			ipAddress: "192.168.1.100",
			userAgent: "Mozilla/5.0",
			data: { dealerId: "dealer_002", fields: ["phone", "address"] },
			errorMessage: null,
			createdAt: new Date("2024-05-01T13:00:00Z"),
		},
		// PURCHASE category
		{
			id: `al_${pad(11)}`,
			userId: USER_IDS.sales1,
			category: "PURCHASE",
			event: "PURCHASE_REGISTERED",
			status: "success",
			priority: "medium",
			ipAddress: "10.0.1.50",
			userAgent: "Mozilla/5.0",
			data: {
				purchaseId: "purch_001",
				customerId: "cust_001",
				source: "dealer",
			},
			errorMessage: null,
			createdAt: new Date("2024-01-20T10:00:00Z"),
		},
		{
			id: `al_${pad(12)}`,
			userId: USER_IDS.sales2,
			category: "PURCHASE",
			event: "INVOICE_UPLOADED",
			status: "success",
			priority: "low",
			ipAddress: "10.0.1.51",
			userAgent: "Mozilla/5.0",
			data: {
				invoiceId: "inv_001",
				purchaseId: "purch_001",
				fileSizeBytes: 512000,
			},
			errorMessage: null,
			createdAt: new Date("2024-01-20T10:05:00Z"),
		},
		{
			id: `al_${pad(13)}`,
			userId: USER_IDS.sales1,
			category: "PURCHASE",
			event: "PURCHASE_FAILED",
			status: "error",
			priority: "high",
			ipAddress: "10.0.1.50",
			userAgent: "Mozilla/5.0",
			data: { customerId: "cust_003", reason: "Product already sold" },
			errorMessage:
				"Product prod_00045 has already been linked to another purchase",
			createdAt: new Date("2024-08-14T15:20:00Z"),
		},
		// USER category
		{
			id: `al_${pad(14)}`,
			userId: USER_IDS.admin,
			category: "USER",
			event: "USER_CREATED",
			status: "success",
			priority: "medium",
			ipAddress: "192.168.1.100",
			userAgent: "Mozilla/5.0",
			data: { newUserId: USER_IDS.sales2, role: "sales" },
			errorMessage: null,
			createdAt: new Date("2024-01-05T09:00:00Z"),
		},
		{
			id: `al_${pad(15)}`,
			userId: USER_IDS.admin,
			category: "USER",
			event: "USER_ROLE_CHANGED",
			status: "success",
			priority: "high",
			ipAddress: "192.168.1.100",
			userAgent: "Mozilla/5.0",
			data: {
				targetUserId: USER_IDS.techSupport2,
				previousRole: "dealer",
				newRole: "technical_support",
			},
			errorMessage: null,
			createdAt: new Date("2024-03-10T11:00:00Z"),
		},
		// WARRANTY category
		{
			id: `al_${pad(16)}`,
			userId: USER_IDS.techSupport1,
			category: "WARRANTY",
			event: "WARRANTY_CONDITION_SET",
			status: "success",
			priority: "medium",
			ipAddress: "10.0.2.10",
			userAgent: "Mozilla/5.0",
			data: { productId: "prod_00031", condition: "valid" },
			errorMessage: null,
			createdAt: new Date("2024-02-06T09:00:00Z"),
		},
		{
			id: `al_${pad(17)}`,
			userId: USER_IDS.techSupport2,
			category: "WARRANTY",
			event: "WARRANTY_REJECTED",
			status: "success",
			priority: "high",
			ipAddress: "10.0.2.11",
			userAgent: "Mozilla/5.0",
			data: {
				productId: "prod_00096",
				reason: "Kerusakan akibat penggunaan tidak sesuai prosedur",
			},
			errorMessage: null,
			createdAt: new Date("2024-07-22T14:00:00Z"),
		},
		// WAITING_LIST category
		{
			id: `al_${pad(18)}`,
			userId: USER_IDS.sales1,
			category: "WAITING_LIST",
			event: "WAITING_LIST_NOTIFIED",
			status: "success",
			priority: "medium",
			ipAddress: "10.0.1.50",
			userAgent: "Mozilla/5.0",
			data: { waitingListId: "wl_009", serialNumber: "SN-ANGLEGRI-00012" },
			errorMessage: null,
			createdAt: new Date("2024-10-01T10:05:00Z"),
		},
		{
			id: `al_${pad(19)}`,
			userId: null,
			category: "WAITING_LIST",
			event: "WAITING_LIST_CREATED",
			status: "success",
			priority: "low",
			ipAddress: "198.51.100.22",
			userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0)",
			data: { serialNumber: "SN-CHAINSAWE-00003", requesterType: "end_user" },
			errorMessage: null,
			createdAt: new Date("2024-11-01T08:30:00Z"),
		},
		// SYSTEM category
		{
			id: `al_${pad(20)}`,
			userId: null,
			category: "SYSTEM",
			event: "SCHEDULED_WARRANTY_EXPIRY_CHECK",
			status: "success",
			priority: "low",
			ipAddress: null,
			userAgent: null,
			data: { checkedCount: 100, expiredCount: 10 },
			errorMessage: null,
			createdAt: new Date("2024-11-01T00:00:00Z"),
		},
		{
			id: `al_${pad(21)}`,
			userId: null,
			category: "SYSTEM",
			event: "DATABASE_BACKUP",
			status: "success",
			priority: "low",
			ipAddress: null,
			userAgent: null,
			data: { backupSize: "512MB", duration: "45s" },
			errorMessage: null,
			createdAt: new Date("2024-11-14T02:00:00Z"),
		},
		{
			id: `al_${pad(22)}`,
			userId: null,
			category: "SYSTEM",
			event: "NOTIFICATION_DISPATCH_FAILED",
			status: "error",
			priority: "high",
			ipAddress: null,
			userAgent: null,
			data: { notificationIds: ["notif_007"], reason: "SMTP timeout" },
			errorMessage: "Failed to send email notification: connection timed out",
			createdAt: new Date("2024-10-22T14:01:00Z"),
		},
	];

	await db.insert(auditLog).values(auditLogData).onConflictDoNothing();
	console.log(`✅ Seeded ${auditLogData.length} audit logs`);
}
